//
// Generated file, do not edit! Created by nedtool 5.6 from apps/agentquartet/common/AQFilterRules.msg.
//

#ifndef __INET_AQFILTERRULES_M_H
#define __INET_AQFILTERRULES_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif


namespace inet {

class Statistics;
class Ace;
class Acl;
class Acls;
} // namespace inet

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk


namespace inet {

/**
 * Class generated from <tt>apps/agentquartet/common/AQFilterRules.msg:19</tt> by nedtool.
 * <pre>
 * class Statistics
 * {
 *     long matchedPackets;
 *     long matchedOctets;
 * }
 * </pre>
 */
class Statistics
{
  protected:
    long matchedPackets = 0;
    long matchedOctets = 0;

  private:
    void copy(const Statistics& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Statistics&);

  public:
    Statistics();
    Statistics(const Statistics& other);
    virtual ~Statistics();
    Statistics& operator=(const Statistics& other);
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    // field getter/setter methods
    virtual long getMatchedPackets() const;
    virtual void setMatchedPackets(long matchedPackets);
    virtual long getMatchedOctets() const;
    virtual void setMatchedOctets(long matchedOctets);
};

/**
 * Class generated from <tt>apps/agentquartet/common/AQFilterRules.msg:24</tt> by nedtool.
 * <pre>
 * class Ace
 * {
 *     string name;
 *     string filterRule;
 *     Statistics statistics;
 * }
 * </pre>
 */
class Ace
{
  protected:
    omnetpp::opp_string name;
    omnetpp::opp_string filterRule;
    Statistics statistics;

  private:
    void copy(const Ace& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Ace&);

  public:
    Ace();
    Ace(const Ace& other);
    virtual ~Ace();
    Ace& operator=(const Ace& other);
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getName() const;
    virtual void setName(const char * name);
    virtual const char * getFilterRule() const;
    virtual void setFilterRule(const char * filterRule);
    virtual const Statistics& getStatistics() const;
    virtual Statistics& getStatisticsForUpdate() { return const_cast<Statistics&>(const_cast<Ace*>(this)->getStatistics());}
    virtual void setStatistics(const Statistics& statistics);
};

/**
 * Enum generated from <tt>apps/agentquartet/common/AQFilterRules.msg:30</tt> by nedtool.
 * <pre>
 * enum ActivationType
 * {
 *     ACTIVITE_WHEN_MITIGATING = 1; //The ACLs is installed only when a mitigation is active for the client.
 *     IMMEDIATE = 2; //The ACL is immediately activated.
 *     DEACTIVATE = 3; //The ACL is maintained by the DOTS server, but it isdeactivated.
 * }
 * </pre>
 */
enum ActivationType {
    ACTIVITE_WHEN_MITIGATING = 1,
    IMMEDIATE = 2,
    DEACTIVATE = 3
};

/**
 * Class generated from <tt>apps/agentquartet/common/AQFilterRules.msg:36</tt> by nedtool.
 * <pre>
 * class Acl
 * {
 *     string name;
 *     string type;
 *     ActivationType activitionType;
 *     int PendingLifetime;
 *     Ace ace[];
 * }
 * </pre>
 */
class Acl
{
  protected:
    omnetpp::opp_string name;
    omnetpp::opp_string type;
    inet::ActivationType activitionType = static_cast<inet::ActivationType>(-1);
    int PendingLifetime = 0;
    Ace *ace = nullptr;
    size_t ace_arraysize = 0;

  private:
    void copy(const Acl& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Acl&);

  public:
    Acl();
    Acl(const Acl& other);
    virtual ~Acl();
    Acl& operator=(const Acl& other);
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getName() const;
    virtual void setName(const char * name);
    virtual const char * getType() const;
    virtual void setType(const char * type);
    virtual inet::ActivationType getActivitionType() const;
    virtual void setActivitionType(inet::ActivationType activitionType);
    virtual int getPendingLifetime() const;
    virtual void setPendingLifetime(int PendingLifetime);
    virtual void setAceArraySize(size_t size);
    virtual size_t getAceArraySize() const;
    virtual const Ace& getAce(size_t k) const;
    virtual Ace& getAceForUpdate(size_t k) { return const_cast<Ace&>(const_cast<Acl*>(this)->getAce(k));}
    virtual void setAce(size_t k, const Ace& ace);
    virtual void insertAce(const Ace& ace);
    virtual void insertAce(size_t k, const Ace& ace);
    virtual void eraseAce(size_t k);
};

/**
 * Class generated from <tt>apps/agentquartet/common/AQFilterRules.msg:44</tt> by nedtool.
 * <pre>
 * class Acls extends FieldsChunk
 * {
 *     Acl acl[];
 * }
 * </pre>
 */
class Acls : public ::inet::FieldsChunk
{
  protected:
    Acl *acl = nullptr;
    size_t acl_arraysize = 0;

  private:
    void copy(const Acls& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Acls&);

  public:
    Acls();
    Acls(const Acls& other);
    virtual ~Acls();
    Acls& operator=(const Acls& other);
    virtual Acls *dup() const override {return new Acls(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual void setAclArraySize(size_t size);
    virtual size_t getAclArraySize() const;
    virtual const Acl& getAcl(size_t k) const;
    virtual Acl& getAclForUpdate(size_t k) { handleChange();return const_cast<Acl&>(const_cast<Acls*>(this)->getAcl(k));}
    virtual void setAcl(size_t k, const Acl& acl);
    virtual void insertAcl(const Acl& acl);
    virtual void insertAcl(size_t k, const Acl& acl);
    virtual void eraseAcl(size_t k);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Acls& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Acls& obj) {obj.parsimUnpack(b);}

} // namespace inet

#endif // ifndef __INET_AQFILTERRULES_M_H

