//
// Generated file, do not edit! Created by nedtool 5.6 from apps/agentquartet/common/AQHeartbeat.msg.
//

#ifndef __INET_AQHEARTBEAT_M_H
#define __INET_AQHEARTBEAT_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif


namespace inet {

class Heartbeat;
} // namespace inet

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk


namespace inet {

/**
 * Class generated from <tt>apps/agentquartet/common/AQHeartbeat.msg:20</tt> by nedtool.
 * <pre>
 * class Heartbeat extends FieldsChunk
 * {
 *     bool peerHbStatus;
 * }
 * </pre>
 */
class Heartbeat : public ::inet::FieldsChunk
{
  protected:
    bool peerHbStatus = false;

  private:
    void copy(const Heartbeat& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Heartbeat&);

  public:
    Heartbeat();
    Heartbeat(const Heartbeat& other);
    virtual ~Heartbeat();
    Heartbeat& operator=(const Heartbeat& other);
    virtual Heartbeat *dup() const override {return new Heartbeat(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual bool getPeerHbStatus() const;
    virtual void setPeerHbStatus(bool peerHbStatus);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Heartbeat& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Heartbeat& obj) {obj.parsimUnpack(b);}

} // namespace inet

#endif // ifndef __INET_AQHEARTBEAT_M_H

